# Generated by Django 5.2.7 on 2025-10-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'invalid': '请输入正确的邮箱格式'}, max_length=254)),
                ('captcha', models.CharField(max_length=6)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
