# Generated by Django 5.2.7 on 2025-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzzikauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchamodel',
            name='email',
            field=models.EmailField(error_messages={'invalid': '请输入正确的邮箱格式'}, max_length=254, unique=True),
        ),
    ]
