# Generated by Django 5.2.7 on 2025-10-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': '博客分类', 'verbose_name_plural': '博客分类'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': '博客评论', 'verbose_name_plural': '博客评论'},
        ),
    ]
